# Generated by Django 5.2.14 on 2026-06-12 13:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WasteRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_wasted', models.DecimalField(decimal_places=4, max_digits=10)),
                ('waste_category', models.CharField(choices=[('Product expired', 'Product Expired'), ('Delivery damaged', 'Delivery Damaged'), ('Counting error', 'Counting Error'), ('Spillage/accidental waste', 'Spillage/Accidental Waste'), ('Void—entered in error', 'Void—Entered in Error'), ('Other', 'Other')], max_length=100)),
                ('notes', models.CharField(blank=True, max_length=200, null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='waste_records', to='inventory.product')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waste_records_recorded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
    ]
