# Generated by Django 5.2.14 on 2026-06-20 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_remove_unit_unique_constraint'),
        ('waste', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wasterecord',
            name='stock_movement',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='waste_record', to='inventory.stockmovement'),
        ),
    ]
