# Generated by Django 5.2.14 on 2026-07-02 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_remove_unit_unique_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='voids',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='voided_by', to='inventory.stockmovement'),
        ),
    ]
