# Generated by Django 5.2.14 on 2026-07-02 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_stockmovement_voids'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='corrects',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='corrected_by', to='inventory.stockmovement'),
        ),
    ]
