# Generated by Django 5.2.14 on 2026-07-02 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_stockmovement_corrects'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='unit_cost_snapshot',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Unit price (per product unit) frozen at the time this movement was recorded. Null if no price existed. Never updated.', max_digits=10, null=True),
        ),
    ]
