# Generated by Django 5.2.14 on 2026-07-18 10:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_stockmovement_unit_cost_snapshot'),
        ('recipes', '0002_recipe_selling_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('IN', 'Stock In'), ('OUT', 'Stock Out'), ('SALE', 'Sale'), ('WASTE', 'Waste'), ('VOID', 'Void — Entered in Error'), ('ADJUSTMENT_IN', 'Adjustment In'), ('ADJUSTMENT_OUT', 'Adjustment Out')], max_length=20),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, help_text='Free-text label, e.g. a table or ticket number.', max_length=50, null=True)),
                ('notes', models.CharField(blank=True, max_length=200, null=True)),
                ('placed_at', models.DateTimeField(auto_now_add=True)),
                ('placed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_placed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-placed_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(help_text='Number of dishes ordered (whole portions).')),
                ('unit_selling_price_snapshot', models.DecimalField(blank=True, decimal_places=2, help_text='Recipe selling price per portion, frozen at order time. Null if the recipe had no selling price set.', max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.order')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_lines', to='recipes.recipe')),
            ],
        ),
    ]
