# Generated by Django 5.2.14 on 2026-07-18 12:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_stockmovement_movement_type_order_orderline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderline',
            name='quantity',
            field=models.PositiveIntegerField(help_text='Number of dishes ordered (whole portions).', validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
