# Generated by Django 5.2.14 on 2026-07-23 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_add_minvalue_validator_orderline_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='reason_category',
            field=models.CharField(blank=True, choices=[('Product expired', 'Product Expired'), ('Delivery damaged', 'Delivery Damaged'), ('Counting error', 'Counting Error'), ('Spillage/accidental waste', 'Spillage/Accidental Waste'), ('Prepared dish wasted', 'Prepared Dish Wasted'), ('Preparation error', 'Preparation Error'), ('Void—entered in error', 'Void—Entered in Error'), ('Other', 'Other')], max_length=100, null=True),
        ),
    ]
