# Generated by Django 5.2.14 on 2026-07-24 11:24

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_alter_stockmovement_reason_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='reason_category',
            field=models.CharField(blank=True, choices=[('Product expired', 'Product Expired'), ('Delivery damaged', 'Delivery Damaged'), ('Counting error', 'Counting Error'), ('Spillage/accidental waste', 'Spillage/Accidental Waste'), ('Prepared dish wasted', 'Prepared Dish Wasted'), ('Preparation error', 'Preparation Error'), ('Stock take adjustment', 'Stock Take Adjustment'), ('Void—entered in error', 'Void—Entered in Error'), ('Other', 'Other')], max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='StockTake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, help_text='Free-text label, e.g. a count reference or date.', max_length=50, null=True)),
                ('notes', models.CharField(blank=True, max_length=200, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('applied_at', models.DateTimeField(blank=True, help_text='Set when the count is applied and adjustment movements are written. Null while the count is still a draft.', null=True)),
                ('counted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_takes_counted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='StockTakeLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_quantity_snapshot', models.DecimalField(decimal_places=4, help_text='System stock at the moment this line was created.', max_digits=10)),
                ('counted_quantity', models.DecimalField(blank=True, decimal_places=4, help_text='Physically counted quantity, in the product unit. Null until counted.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('discrepancy', models.DecimalField(blank=True, decimal_places=4, help_text='counted_quantity minus system_quantity_snapshot, stored when the stock take is applied.', max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_take_lines', to='inventory.product')),
                ('stock_take', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.stocktake')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('stock_take', 'product'), name='unique_product_per_stock_take')],
            },
        ),
    ]
