# Generated by Django 5.2.14 on 2026-07-12 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='selling_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Menu selling price per yield unit. Null if not yet set; food-cost percent is not computed without it.', max_digits=10, null=True),
        ),
    ]
